name = "Catalog Doctor"
client_id = "34df8619b2978ecc0a1e7f392b62fe67"
application_url = "https://catalog-doctor.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://catalog-doctor.vercel.app/auth/callback",
  "https://catalog-doctor.vercel.app/auth/shopify/callback",
  "https://catalog-doctor.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
