name = "Catalog Doctor"
client_id = "34df8619b2978ecc0a1e7f392b62fe67"
application_url = "https://cradle-exposure-taxation-digit.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [
  "https://cradle-exposure-taxation-digit.trycloudflare.com/auth/callback",
  "https://cradle-exposure-taxation-digit.trycloudflare.com/auth/shopify/callback",
  "https://cradle-exposure-taxation-digit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
